### ISSUE TITLE
error with ire installation

### ISSUE THREAD

**Issue by cryax** [ip1981/ire#1]
I got this error after ran the command:
cabal install --ghc-options="-optl=-Wl,-rpath,$darknet/lib" --extra-include-dirs "$darknet/include" --extra-lib-dirs "$darknet/lib"
cabal: Error: some packages failed to install:
haskell-src-exts-1.19.1 failed during the configure step. The exception was:
ExitFailure 1
haskell-src-meta-0.8.0.1 depends on haskell-src-exts-1.19.1 which failed to
install.
interpolatedstring-perl6-1.0.0 depends on haskell-src-exts-1.19.1 which failed
to install.
ire-0.0.0 depends on haskell-src-exts-1.19.1 which failed to install.

**Comment by ip1981** [comment]
Try this https://github.com/ip1981/ire/commit/1c621db4b5b0d78ae6b2f79c71122c6cca2a0815.

Although, the problem is with building dependencies.

**Comment by cryax** [comment]
thanks now I got another error:
Resolving dependencies...
Configuring ire-0.0.0...
Failed to install ire-0.0.0
Build log ( /home/younet/.cabal/logs/ire-0.0.0.log ):
Configuring ire-0.0.0...
setup-Simple-Cabal-1.22.5.0-x86_64-linux-ghc-7.10.3: Missing dependency on a
foreign library:
* Missing C library: darknet
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
cabal: Error: some packages failed to install:
ire-0.0.0 failed during the configure step. The exception was:
ExitFailure 1

**Comment by ip1981** [comment]
You need to build and install somewhere this library: https://github.com/ip1981/darknet
Use CMake, there are only two files to install.

Then `export darknet=/path/to/darknet` before building ire.

**Comment by ip1981** [comment]
Disable GPU for now, it does not work yet.

**Comment by cryax** [comment]
Can I build with disabled GPU?

**Comment by cryax** [comment]
Thanks for your help

**Comment by ip1981** [comment]
Like `cmake -DENABLE_CUDA=OFF`
